class Types:
    TIMETABLE = "time_table"
    TIMETABLE_NAME = "time_table_name"
    INSTITUTION_PRIMARY = "primary"
    INSTITUTION_SECONDARY = "secondary"
    INSTITUTION_COLLEGE = "college"
    INSTITUTION_TYPE = "institution_type"

    INSTITUTION_NAME = "institution_name"
    TIME_SLOT_LENGTH = "time_slot_length"
    DAYS_PER_CYCLE = "days_per_cycle"
    SLOTS_PER_DAY = "slots_per_day"
    BREAKING_SLOTS = "break_slots"
    BLOCK_SLOTS = "block_slots"

    SUBJECTS = "subjects"
    SUBJECT = "subject"
    MODULE = "module"
    MODULES = "modules"
    SUBJECT_PRIMARY_VENUE = "primary_venue"
    SUBJECT_PRIMARY_TEACHER = "primary_teacher"

    VENUES = "venues"
    VENUE = "venue"
    VENUE_PRIMARY = "primary"

    TEACHER = "teacher"
    TEACHERS = "teachers"
    LECTURER = "lecturer"
    LECTURERS = "lecturers"
    UNAVAILABLE = "unavailable"

    CLASSES = "classes"
    CLASS = "class"
    COURSES = "courses"
    COURSE = "course"

    SEQUENCE = "sequence"
    NAME = "name"
    SHORT_NAME = "short_name"
    EVENTS = "events"
    LEVEL = "level"
    DATA = "data"
    BLOCKS = "blocks"
    CODE = "code"
    COURSE_MODULE_CODE = "course_module_code"
